Add switch statement for intensity profiles
geoffrey4444/NumericalCoatingThermalNoise pull request #1
Opened 2018-06-09 19:34 UTC by ndemos

Add missing switch statement for loss angle
Decouple substrate height from cylinder radius

I know these should have been 3 separate commits, but hopefully still okay. Just starting to get more comfortable with git.

Code tested using previous default settings, except changing max cycles to 7. Here is the output from diff on the Energy files.

diff new/Run/Energy.dat old/Run/Energy.dat 
12c12
< 3 0.014610113175338 0.014310571480188 0.00029954169514985 8.6873193203975e-18 6.2842860113827e-18 1.072202255395e-17
---
> 3 0.014610113175338 0.014310571480188 0.00029954169514985 8.6873193203976e-18 6.2842860113827e-18 1.072202255395e-17
15c15
< 6 0.014949195050855 0.014633241095824 0.00031595395503144 8.7847126579797e-18 6.4541521458798e-18 1.090079154949e-17
---
> 6 0.014949195050854 0.014633241095825 0.00031595395502971 8.78471265798e-18 6.4541521458621e-18 1.090079154948e-17

2018-06-09 20:22 UTC, geoffrey4444 requested changes

2018-06-09 20:22 UTC, geoffrey4444 commented on QuasistaticBrownianThermalNoise/QuasistaticBrownianThermalNoise.cpp
Do you ever use the commented out lines? If not, remove them. If so, make them selectable with a switch?

2018-06-09 20:22 UTC, geoffrey4444 commented on QuasistaticBrownianThermalNoise/QuasistaticBrownianThermalNoise.cpp
> +        case(kAlGaAs):
Shouldn’t the switch set Yijkl as well as the loss angles?

2018-06-09 20:25 UTC, geoffrey4444 commented
Would be cool if you could set up the energy test with ctest

2018-06-11 15:32 UTC, ndemos commented on QuasistaticBrownianThermalNoise/QuasistaticBrownianThermalNoise.cpp
> +        case(kAlGaAs):
This is already done for Yijkl.

2018-06-11 22:22 UTC, geoffrey4444 requested changes
One more quick change, then I'm happy to approve. 

Then, next (separate commit), do you think you could set all switch values to be read in from an input file? Then you can write little tests that read an input file, get a result, and compare to a hard-coded expected result. Eventually, would be great if we could use ctest to run them, but first priority is to get some tests, period.

2018-06-11 22:22 UTC, geoffrey4444 commented on QuasistaticBrownianThermalNoise/QuasistaticBrownianThermalNoise.cpp
> +      myValue /= 8 * M_PI * r0 * r0;
Sorry I missed this before, but be aware that some older versions of python might treat your numbers as integers, not floats, if no decimal points. To be safe, Please put ".0" after all hard-coded floating-point numbers.

2018-06-12 15:21 UTC, geoffrey4444 approved these changes

2018-06-12 18:20 UTC, merged